# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------
QT+= core widget
TEMPLATE = app
TARGET = VegaTest
DESTDIR = ../Debug
CONFIG += debug
DEPENDPATH += .
MOC_DIR += .
OBJECTS_DIR += debug
UI_DIR += .
RCC_DIR += .
include(VegaTest.pri)
win32:RC_FILE = VegaTest.rc
